name: Build plugin
on: 
  push:
    branches: ['master']
jobs:
  Linux-Build:
    name: Linux build
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y libasound2-dev libjack-jackd2-dev \
              ladspa-sdk \
              libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
              libwebkit2gtk-4.0-dev \
              libglu1-mesa-dev mesa-common-dev
      - name: Make release
        working-directory: ./Builds/LinuxMakefile
        run: make -j4 CONFIG=Release
      - name: Publish plugin
        uses: actions/upload-artifact@v2
        with:
          name: Reverberator
          path: ./Builds/LinuxMakefile/build/Reverberator.vst3